import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../services/api'
import Message from '../components/Message'

export default function Booking(){
 const [params]=useSearchParams(); const [services,setServices]=useState([]); const [form,setForm]=useState({customerName:'',phone:'',bikeModel:'',serviceId:params.get('service')||'',preferredDate:'',notes:''}); const [success,setSuccess]=useState(null); const [error,setError]=useState(''); const [reference,setReference]=useState(''); const [found,setFound]=useState(null)
 useEffect(()=>{api('/services').then(setServices).catch(e=>setError(e.message))},[])
 const change=e=>setForm({...form,[e.target.name]:e.target.value})
 async function submit(e){e.preventDefault();setError('');setSuccess(null);try{const result=await api('/bookings',{method:'POST',body:JSON.stringify({...form,serviceId:Number(form.serviceId)})});setSuccess(result);setForm({...form,customerName:'',phone:'',bikeModel:'',preferredDate:'',notes:''})}catch(err){setError(err.message)}}
 async function track(e){e.preventDefault();setFound(null);setError('');try{setFound(await api(`/bookings/reference/${reference.trim()}`))}catch(err){setError(err.message)}}
 return <section className="section container"><div className="page-title"><span className="eyebrow">Service workflow</span><h1>Request and track a booking</h1><p>No online payment is required. RideNShine confirms the date and the customer pays at the shop.</p></div><div className="two-columns"><form className="panel form" onSubmit={submit}><h2>New booking request</h2><Message type="error">{error}</Message>{success&&<Message type="success">Request received. Save your reference: <strong>{success.referenceCode}</strong></Message>}<label>Customer name<input name="customerName" value={form.customerName} onChange={change} required/></label><label>Phone number<input name="phone" value={form.phone} onChange={change} placeholder="+880..." required/></label><label>Motorcycle model<input name="bikeModel" value={form.bikeModel} onChange={change} required/></label><label>Service<select name="serviceId" value={form.serviceId} onChange={change} required><option value="">Select a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} — ৳{s.price}</option>)}</select></label><label>Preferred date<input type="date" name="preferredDate" min={new Date().toISOString().slice(0,10)} value={form.preferredDate} onChange={change} required/></label><label>Notes<textarea name="notes" value={form.notes} onChange={change} placeholder="Describe the problem or request"/></label><button className="button" type="submit">Submit booking request</button></form><div><form className="panel form" onSubmit={track}><h2>Track existing booking</h2><label>Booking reference<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="RNS-XXXXXXXX" required/></label><button className="button ghost" type="submit">Check status</button></form>{found&&<div className="panel booking-result"><span className={`status ${found.status.toLowerCase()}`}>{found.status.replace('_',' ')}</span><h3>{found.referenceCode}</h3><p><strong>{found.service.name}</strong></p><p>{found.customerName} • {found.bikeModel}</p><p>Preferred date: {found.preferredDate}</p></div>}</div></div></section>
}
