import { useEffect, useState } from 'react'
import { api } from '../services/api'
import Message from '../components/Message'
export default function Reviews(){
 const [reviews,setReviews]=useState([]); const [form,setForm]=useState({customerName:'',rating:5,comment:'',imageUrl:''}); const [message,setMessage]=useState(''); const [error,setError]=useState('')
 const load=()=>api('/reviews').then(setReviews).catch(e=>setError(e.message)); useEffect(load,[])
 async function submit(e){e.preventDefault();setMessage('');setError('');try{await api('/reviews',{method:'POST',body:JSON.stringify({...form,rating:Number(form.rating)})});setMessage('Thank you. Your review was sent for admin approval.');setForm({customerName:'',rating:5,comment:'',imageUrl:''})}catch(err){setError(err.message)}}
 return <section className="section container"><div className="page-title"><span className="eyebrow">Customer trust</span><h1>Reviews and service photos</h1><p>New reviews are moderated before they become public. Customers may include a public image link.</p></div><div className="two-columns"><div><h2>Approved reviews</h2>{reviews.length===0?<div className="empty">No approved reviews yet. Submit the first verified review.</div>:reviews.map(r=><article className="review" key={r.id}>{r.imageUrl&&<img src={r.imageUrl} alt="Customer motorcycle"/>}<div className="stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><p>“{r.comment}”</p><strong>{r.customerName}</strong></article>)}</div><form className="panel form" onSubmit={submit}><h2>Share feedback</h2><Message type="success">{message}</Message><Message type="error">{error}</Message><label>Name<input value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})} required/></label><label>Rating<select value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label><label>Comment<textarea value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})} required/></label><label>Public photo URL (optional)<input type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/></label><button className="button">Submit for approval</button></form></div></section>
}
